[package]
name = "ditto-test-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dittolive-ditto = "1.1.1"
dotenv = "0.15.0"
serde_json = "1.0.48"
